app/models.py
from . import db,login_manager
from flask_login import UserMixin,current_user
from werkzeug.security import generate_password_hash,check_password_hash
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model,UserMixin):
    __tablename__='users'
    id =db.Column(db.Integer(),primary_key = True)
    username = db.Column(db.String(255),unique = True)
    email = db.Column(db.String(255),unique = True , index = True)
    password_secure = db.Column(db.String(255))
    image_pic_path = db.Column(db.String(255))
    posts = db.relationship('Post',backref = 'user',lazy="dynamic")
    comments = db.relationship('Comment',backref = 'user',lazy="dynamic")


    @property
    def password(self):

        raise AttributeError('You cannot read the password attribute')

        
    @password.setter
    def password(self, password):
        self.password_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_secure,password)

    
    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'

class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer(),primary_key = True)
    title = db.Column(db.String(255),nullable = False)
    category = db.Column(db.String(255), index = True)
    description = db.Column(db.Text(),nullable = False)
    profile_pic_path = db.Column(db.String(255))
    content = db.Column(db.Text(),nullable = False)
    posted = db.Column(db.DateTime, default = datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    comments = db.relationship('Comment',backref = 'post',lazy="dynamic")

      
    def save_post(self):

        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'Post {self.title}'


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer(),primary_key = True)
    content =  db.Column(db.Text(),nullable = False)
    post_id = db.Column(db.Integer,db.ForeignKey('posts.id'))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

    

    def __repr__(self):
        return f'Comment {self.content}'

app/main/forms.py
from flask_wtf import  FlaskForm
from wtforms import StringField,SelectField,TextAreaField,SubmitField
from wtforms.validators import Required
class UpdatePostForm(FlaskForm):
    title=StringField('Title', validators=[Required()])
    category=SelectField('Category',choices=[('Medical','Medical'),('Memorial','Memorial'),('Education','Education'),('Sports','Sports'),('Emergency','Emergency')], validators=[Required()])
    description=StringField('Title', validators=[Required()])
    content=TextAreaField('Your Post.', validators=[Required()])
    submit=SubmitField('save')
class PostForm(FlaskForm):
    title=StringField('Title', validators=[Required()])
    description=StringField('Description', validators=[Required()])
    category=SelectField('Category',choices=[('Medical','Medical'),('Memorial','Memorial'),('Education','Education'),('Sports','Sports'),('Emergency','Emergency')], validators=[Required()])
    image = StringField('Image url',validators = [Required()])
    content=TextAreaField('Your Post', validators=[Required()])
    submit=SubmitField('Post')
class CommentForm(FlaskForm):
    comment=TextAreaField('Leave a comment',validators=[Required()])
    submit=SubmitField('Comment')

app/__init__.py
from flask import Flask 
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail



login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config):
    app = Flask(__name__)

    app.config.from_object(config_options[config])

    # Initializing flask extensions
    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)


    # configure UploadSet
    configure_uploads(app,photos)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)



    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,forms

app/main/views.py
from flask import render_template,url_for,abort,redirect,request
from . import main
from flask_login import login_user,login_required,current_user
# from .forms import RegistrationForm,LoginForm
from ..models import User,Post,Comment
from .. import db,photos
from .forms import UpdatePostForm,PostForm,CommentForm
# import requests

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/ufund')
def fundraiser():
    postes=Post.query.all()
    medical=Post.query.filter_by(category='Medical').all()
    memorial=Post.query.filter_by(category='Memorial').all()
    education=Post.query.filter_by(category='Education').all()
    sports=Post.query.filter_by(category='Sports').all()
    emergency=Post.query.filter_by(category='Emergency').all()
    return render_template('funds.html',medical=medical,memorial=memorial,postes=postes,education=education,sports=sports,emergency=emergency)



@main.route('/comment/<int:post_id>',methods=['GET','POST'])
# @login_required
def comment(post_id):
    form=CommentForm()
    post=Post.query.get(post_id)
    all_comments=Comment.query.filter_by(post_id=post_id).all()
    if form.validate_on_submit():
        comment=form.comment.data
        post_id=post_id
        # user_id=current_user._get_current_object().id
        new_comment=Comment(comment=comment,post_id=post_id)
        new_comment.save_c()
        return redirect(url_for('.comment',post_id=post_id))
    return render_template('comment.html',form=form,post=post,all_comments=all_comments)
@main.route ('/index/<int:post_id>delete',methods=['GET','POST'])
@login_required
def delete(post_id):
    current_post=Post.query.filter_by(id=post_id).first()
    # if current_post
    if current_post.user != current_user:
        abort(403)
    db.session.delete(current_post)
    db.session.commit()
    return redirect(url_for('.index'))
@main.route('/index/<int:id>/delet',methods=['GET','POST'])
@login_required
def delet(id):
    comment= Comment.query.filter_by(id = id).first()
    if comment is None:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('main.fund'))
    # return render_template('comment.html',current_post=current_post)
@main.route('/profile/<int:post_id>/',methods=['GET','POST'])
@login_required
def update_post(post_id):
    current_post= Post.query.filter_by(id = post_id).first()
    if current_post.user != current_user:
        abort(403)
    form=UpdatePostForm()
    if form.validate_on_submit():
        current_post.title=form.title.data
        current_post.category=form.category.data
        current_post.post=form.post.data
        # db.session.add(current_post)
        db.session.commit()
        return redirect(url_for('.index'))
    elif request.method=='GET':
        form.title.data=current_post.title
        form.category.data=current_post.category
        form.post.data=current_post.post
    return render_template('comment.html',form=form)


@main.route('/user/<name>/update/pic',methods=['GET','POST'])
@login_required
def update_pic(name):
    user=User.query.filter_by(username=name).first()
    if 'photo' in request.files:
        filename=photos.save(request.files['photo'])
        path=f'photos/{filename}'
        user.image_pic_path=path
        db.session.commit()
        return redirect(url_for('main.index',name=name))
    return render_template('profile.html')
    
@main.route('/create',methods = ['GET','POST'])
@login_required
def add_post():
    form = PostForm()
    if form.validate_on_submit():
        Post.profile_pic_path = form.image.data 
        user_id = current_user
        new_fund = Post(title = form.title.data, category = form.category.data,description=form.description.data,content = form.content.data,user_id=current_user._get_current_object().id, profile_pic_path = form.image.data )
        new_fund.save_post()
    
        return redirect(url_for('.funds'))
    title = 'Add a post'
    return render_template('create.html',title = title,form = form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to UFund</title>
    {%  block styles %}
    {{super()}}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/styles.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">

    <style>
        /* #header {
            position: fixed;
            background: #22242A;
            margin-top: 0;
            padding: 30px;
            width: 100%;
            height: 40px;
        }

        .left_area h3 {
            color: #fff;
            margin: 0;
            text-transform: uppercase;
            font-size: 22px;
            font-weight: 900;

        }

        .left_area span {
            color: #1DC4E7;
        }

        .logout-bn {
            padding: 5px;
            background: #19b303;
            text-decoration: none;
            float: right;
            margin-top: -30px;
            margin-right: 40px;
            border-radius: 2px;
            font-size: 15px;
            font-weight: 600;
            color: #fff;
            transition: 0.5s;
            transition-property: background;

        }

        .logout_btn:hover {
            background: #0D9DBB;
        }

        .sidebar {
            background: #2F323A;
            margin-top: 70px;
            padding-top: 30px;
            position: fixed;
            left: 0;
            width: 250px;
            height: 100%;
            transition: 0.5s;
            transition-property: left;
        }

        .sidebar .profile_image {
            width: 100px;
            height: 100px;
            border-radius: 100px;
            margin-bottom: 10px;
        }

        .sidebar h4 {
            color: #ccc;
            margin-top: 0;
            margin-bottom: 20px;
        }

        .sidebar a {
            color: #fff;
            display: block;
            width: 100%;
            line-height: 60px;
            text-decoration: none;
            padding-left: 40px;
            box-sizing: border-box;
            transition: 0.5s;
            transition-property: background;

        }

        .sidebar a:hover {
            background: #19B303;
        }

        .sidebar i {
            padding-right: 10px;
        }

        label #sidebar_btn {
            z-index: 1;
            color: rgb(22, 21, 21);
            position: fixed;
            cursor: pointer;
            font-size: 20px;
            left: 300px;
            margin: 5px 0;
            transition: 0.5s;
            transition-property: color;
        }

        label #sidebar_btn:hover {
            color: #19b3d3;
        }

        #check:checked~.sidebar {
            left: -190px;
        }

        #check:checked~.sidebar a span {
            display: none;

        }

        #check:checked~.sidebar a {
            font-size: 20px;
            margin-left: 170px;
            width: 80px;
        } */

        /* .content {
            margin-left: 250px;
            /* background: url('https://images.unsplash.com/photo-1506869673173-31eba16560ab?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80') no-repeat; */
        /* background-position: center;
            background-size: cover;
            height: 100vh;
            transition: 0.5s;
        } */
        /* #check:checked~.content {
            margin-left: 60px; */
        /* }

        #check {
            display: none;
        }  */
        html,
        body {
            /* overflow: hidden; */
            height: 100%;
        }

        body {
            padding: 0%;
            margin: 0;
        }

        .header {
            background: #22242A;
            width: 100%;
            height: 60px;
            position: fixed;
            z-index: 10;


        }

        .left_area h3 {
            color: #fff;
            margin: 0;
            text-transform: uppercase;
            font-size: 22px;
            font-weight: 900;
            z-index: 20;
            margin-left: 50px;
            position: absolute;



        }

        .left_area span {
            color: #1DC4E7;
            font-size: 25px;
        }



        .sidebarIconToggle {
            color: #fff;
            width: 22px;
            height: 22px;
            position: absolute;
            z-index: 20;
            top: 22px;
            left: 15px;
            font-size: 20px;
            cursor: pointer;
        }

        .sidebarIconToggle:hover {
            color: #19b3d3;
        }



        #sidebarMenu {
            font-size: 12px;
            height: 100%;
            position: fixed;
            left: 0;
            top: 0;
            width: 250px;
            margin-top: 60px;
            background-color: #2e86de;
            transform: translateX(-250px);
            transition: transform 250ms ease-in-out;
        }

        #openSidebarMenu:checked~#sidebarMenu {
            transform: translateX(0);

        }

        .menu {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .menu li {
            color: #fff;
            border-bottom: 1px solid rgba(255, 255, 255, 0.10);
        }

        .menu li a {
            color: #fff;
            display: block;
            text-decoration: none;
            text-transform: uppercase;
            padding: 20px;
            transition: 0.5s;
            transition-property: background;
        }
        img#prof{
            margin-top: 20px;
            margin-left: 65px;
            box-shadow: inset 0 0 25px 25px #fff;
        }




        .menu li a:hover {
            background: #19B303;
        }
    </style>


    {% endblock %}

</head>

<body>
    {% block navbar %}
    {% include 'navbar.html' %}
    {% endblock %}
    {% block content %}




    {% endblock %}
    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    {% endblock %}
</body>

</html>

app/templates/create.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block styles %}
{{super()}}
<style>
  .container{
      margin-top:10%;
      border:1px solid rgb(253, 249, 249);
      border-radius: 10px;
      width: 50%;
      padding: 10px 30px;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  }
  input[type=submit]{
      background-color: #00b7ff;
      color: white;
  }
</style>

{% endblock %}
{% block content %}
{{super()}}

<div class="container">
    <div class="row">
        <div class="col-md-2"> </div>
        <div class="col-md-8">
            <h3 class="text-center">Add a fundraiser</h3>
            {{wtf.quick_form(form)}}

        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock%}

app/templates/funds.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block styles%}
{{ super() }}
<style>
    .container {
        margin-left: 250px;
        
        height: 100vh;
        transition: 0.5s;
    }

    #check:checked~.container {
        margin-left: 60px;
    }
</style>

{% endblock %}
{% block content %}
<div class="container">

    <h2 class="text-center" style="font-family: 'Cinzel', serif; text-decoration: underline; margin-bottom: 30px;">
        Recent Fundraiser</h2>
        {{macro.getFund(education)}}
        
</div>



{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{%  block styles %}
{{super()}}
<style>
    .content {
        margin-left: 250px;

        height: 100vh;
        transition: 0.5s;
    }

    #check:checked~.content {
        margin-left: 60px;
    }
</style>
{% endblock %}

{% block content %}

{% endblock %}

app/templates/macros.html
{% macro getFund(posts) %}

{% if posts %}
{% for fund in posts %}

<div class="card-deck">
    <div class="card">
        <img class="card-img-top" src="{{fund.profile_pic_path}}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{fund.title}}</h5>
            <h6 class="card-subtitle">{{fund.description}}</h6>
            <p class="card-text">{{fund.content| truncate (100)}}</p>
            <p class="card-text"><small class="text-muted">{{fund.posted.strftime('%B %d, %Y')}}</small></p>
        </div>
    </div>


</div>
{% endfor %}

{% else %}
<div class="card w-90 mb-3">
    <div class="card-body">
        <p class="card-title">No Fundraiser yet</p>
    </div>
</div>
{% endif %}
{% endmacro %}

app/templates/navbar.html
<div class="header"></div>
<input type="checkbox" id="openSidebarMenu">
<label for="openSidebarMenu" class="sidebarIconToggle">
    <i class="fas fa-bars" id='sidebar_btn'></i>

</label>

<div class="left_area">
    <h3>U<span>Fund</span></h3>
</div>
<div id="sidebarMenu">

    {% if current_user.image_pic_path %}
    <a href="{{url_for('main.update_pic',name=current_user.username)}}" id='pic'><img class="rounded-circle z-depth-2" id='prof'
            src="{{url_for('static',filename=current_user.image_pic_path)}}" alt="" width='100' data-holder-rendered="true"></a>

    {% else %}
    <a href="{{url_for('main.update_pic',name=current_user.username)}}" id='pic'><img class="rounded-circle z-depth-2" id='prof'
            src="https://res.cloudinary.com/ucynthy12/image/upload/v1607543371/kisspng-avatar-user-profile-male-logo-profile-icon-5b238cb002ed52.870627731529056432012-removebg-preview_seksvj.png"
            alt="" width='100' data-holder-rendered="true"></a>
    {% endif %}
    <h4 class="text-center"
        style="font-size: 20px;text-transform: capitalize;font-weight: bold;margin:5px;color: white;">
        {{current_user.username}}</h4>


    <ul class="menu">
        <li><a href="/"><i class="fas fa-desktop"></i>&nbsp;&nbsp;<span>Home</span></a></li>

        <li><a href="/ufund"><i class="fas fa-cogs"></i>&nbsp;&nbsp;<span>Fundraiser</span></a></li>
        <li><a href=""><i class="fas fa-search"></i>&nbsp;&nbsp;<span>Search</span></a></li>
        <li><a href="/create"><i class="fas fa-plus"></i>&nbsp;&nbsp;<span>Add a fundraiser</span></a></li>
        {% if current_user.is_authenticated %}
        <li><a href="{{url_for('auth.logout')}}"><i class="fas fa-user-plus"></i>&nbsp;&nbsp;<span>Logout</span></a>
        </li>

        {% else %}
        <li><a href="{{url_for('auth.register')}}"><i class="fas fa-user-plus"></i>&nbsp;&nbsp;<span>Sign up</span></a>
        </li>
        <li><a href="{{url_for('auth.login')}}"><i class="fas fa-user-plus"></i>&nbsp;&nbsp;<span>Login</span></a>
        </li>


        {% endif %}

    </ul>
</div>
<div class="main">

</div>

app/templates/profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block styles%}
{{ super() }}
<style>
    input[type=submit]{
        background-color: rgb(80, 136, 189);
        color:white;
        margin: 10px auto;
        width: 30%;
        border-radius: 2px;
        padding: 6px;
        margin-left:30%;
    }
    input[type=file]{
        margin-top: 15%;
        margin-left: 18%;
        padding: 5px;
        width: 60%;
    }

</style>
{% endblock %}
{% block content %}
{% if current_user %}
<div class="container">
    <form action="{{url_for('main.update_pic',name=current_user.username)}}" method="post"
        enctype="multipart/form-data">
        <input type="file" name="photo" class="form-control" required>
        <input type="submit">
    </form>
</div>
{% endif %}
{% endblock %}s